name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  setup:
    name: Common Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-


  lint:
    needs: [ setup ]
    name: Run Android Lint
    runs-on: ubuntu-latest

    steps:
      - name: Run Android Lint
        run: ./gradlew lint

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results.html

  unit-test:
    needs: [ lint, setup ]
    name: Run Android test
    runs-on: ubuntu-latest

    steps:
      - name: Run Android test
        run: ./gradlew test

      - name: Upload test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: app/build/reports/tests/testDebugUnitTest/

  package:
    needs: [ unit-test, setup ]
    name: Build debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: app.apk
          path: app/build/outputs/apk/debug/app-debug.apk




